# VULNERABLE CVE-2025-15467
FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# Sleep for tool testing
CMD ["sleep", "1000"]
